In [ ]:
import pandas as pd

hello

In [ ]:
import pandas as pd
df=pd.read_csv('adult_eda.csv')
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [11]:
df[df['sex']=="Female"]

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
4,28,Private,338409,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14.0,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5.0,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
8,31,Private,45781,Masters,14.0,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
12,23,Private,122272,Bachelors,13.0,Never-married,Adm-clerical,NaN,White,Female,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32546,37,Private,198216,Assoc-acdm,12.0,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States,<=50K
32549,43,State-gov,255835,Some-college,10.0,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K
32556,27,Private,257302,Assoc-acdm,12.0,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32558,58,Private,151910,HS-grad,9.0,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9.0,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [17]:
df[df["salary"]>'20K']

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12.0,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9.0,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9.0,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9.0,Never-married,Adm-clerical,NaN,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9.0,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

find dublicate rows and drop duplicate rows

In [19]:
df.duplicated().value_counts()

False    32537
True        24
Name: count, dtype: int64

drop duplicate

In [20]:
df=df.drop_duplicates()
df.duplicated().value_counts()

False    32537
Name: count, dtype: int64

Find the shape of the data.

In [22]:
df.shape

(32537, 15)

: Find the basic stats of the data.

In [23]:
df.describe()

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
count,32537.000000,3.253700e+04,31735.000000,32537.000000,32537.000000,32537.000000
mean,38.585549,1.897808e+05,10.084008,1078.443741,87.368227,40.440329
std,13.637984,1.055565e+05,2.575060,7387.957424,403.101833,12.346889
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.369930e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [24]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
       'salary'],
      dtype='object')

Step-6: Rename the columns(optional)

In [1]:
df.columns=df.columns.str.replace("_","_")
df.columns

df.rename(columns={'age':'agee'},inplace=True)
df.columns

NameError: name 'df' is not defined

In [4]:
import pandas as pd
df=pd.read_csv('adult_eda.csv')
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13.0,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9.0,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7.0,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

NameError: name 'df' is not defined

In [6]:
import pandas as pd

df=pd.read_csv('Titanic-Dataset.csv')
df.head()
df.info()
df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [7]:
df.duplicated().value_counts

<bound method IndexOpsMixin.value_counts of 0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Length: 891, dtype: bool>

data collection 

Numrical( Quantitive) Data Analysis

In [1]:
!pip install matplotlib

Collecting matplotlib
  Downloading matplotlib-3.10.1-cp313-cp313-win_amd64.whl.metadata (11 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.1-cp313-cp313-win_amd64.whl.metadata (5.4 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.56.0-cp313-cp313-win_amd64.whl.metadata (103 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.4.8-cp313-cp313-win_amd64.whl.metadata (6.3 kB)
Requirement already satisfied: numpy>=1.23 in c:\users\yrahu\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.2.3)
Requirement already satisfied: packaging>=20.0 in c:\users\yrahu\appdata\roaming\python\python313\site-packages (from matplotlib) (24.2)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-11.1.0-cp313-cp313-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=2.3.1 (from matplotlib)
  Downloading pyparsing-3.2.1-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\yrahu\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\yrahu\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.10.1-cp313-cp313-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   --- ------------------------------------ 0.8/8.1 MB 6.6 MB/s eta 0:00:02
   --- ------------------------------------ 0.8/8.1 MB 6.6 MB/s eta 0:00:02
   ------- -------------------------------- 1.6/8.1 MB 2.3 MB/s eta 0:00:03
   ---------- ----------------------------- 2.1/8.1 MB 2.3 MB/s eta 0:00:03
   ------------- -------------------------- 2.6/8.1 MB 2.5 MB/s eta 0:00:03
   -------------- ------------------------- 2.9/8.1 MB 2.4 MB/s eta 0:00:03
   -------------- ------------------------- 2.9/8.1 MB 2.4 MB/s eta 0:00:03
   -------------- ------------------------- 2.9/8.1 MB 2.4 MB/s eta 0:00:03
   -------------- ------------------------- 2.9/8.1 MB 2.4 MB/s eta 0:00:03
   --------------- ------------------------ 3.1/8.1 MB 1.5 MB/s eta 0:00:04
   --------------- ------------------------ 3.1/8.1 MB 1.5 MB/s eta 0:00:04
   ---------------- ----------------------- 3.4/8.1 MB 1.3 MB/s eta 0:00:04
   ---------------- ----------------------- 3.4/8.1 MB 1.3 MB/s eta 0:00:04
   ---------------- ----------------------- 3.4/8.1 MB 1.3 MB/s eta 0:00:04
   ---------------- ----------------------- 3.4/8.1 MB 1.3 MB/s eta 0:00:04
   ------------------ --------------------- 3.7/8.1 MB 1.1 MB/s eta 0:00:05
   ------------------ --------------------- 3.7/8.1 MB 1.1 MB/s eta 0:00:05
   ------------------ --------------------- 3.7/8.1 MB 1.1 MB/s eta 0:00:05
   ------------------- -------------------- 3.9/8.1 MB 927.8 kB/s eta 0:00:05
   ------------------- -------------------- 3.9/8.1 MB 927.8 kB/s eta 0:00:05
   ------------------- -------------------- 3.9/8.1 MB 927.8 kB/s eta 0:00:05
   ------------------- -------------------- 3.9/8.1 MB 927.8 kB/s eta 0:00:05
   ------------------- -------------------- 3.9/8.1 MB 927.8 kB/s eta 0:00:05
   ------------------- -------------------- 3.9/8.1 MB 927.8 kB/s eta 0:00:05
   -------------------- ------------------- 4.2/8.1 MB 759.3 kB/s eta 0:00:06
   -------------------- ------------------- 4.2/8.1 MB 759.3 kB/s eta 0:00:06
   -------------------- ------------------- 4.2/8.1 MB 759.3 kB/s eta 0:00:06
   -------------------- ------------------- 4.2/8.1 MB 759.3 kB/s eta 0:00:06
   ---------------------- ----------------- 4.5/8.1 MB 708.3 kB/s eta 0:00:06
   ---------------------- ----------------- 4.5/8.1 MB 708.3 kB/s eta 0:00:06
   ---------------------- ----------------- 4.5/8.1 MB 708.3 kB/s eta 0:00:06
   ----------------------- ---------------- 4.7/8.1 MB 664.3 kB/s eta 0:00:06
   ----------------------- ---------------- 4.7/8.1 MB 664.3 kB/s eta 0:00:06
   ----------------------- ---------------- 4.7/8.1 MB 664.3 kB/s eta 0:00:06
   ----------------------- ---------------- 4.7/8.1 MB 664.3 kB/s eta 0:00:06
   ------------------------ --------------- 5.0/8.1 MB 638.7 kB/s eta 0:00:05
   --------------------------- ------------ 5.5/8.1 MB 681.1 kB/s eta 0:00:04
   ---------------------------- ----------- 5.8/8.1 MB 696.6 kB/s eta 0:00:04
   ---------------------------- ----------- 5.8/8.1 MB 696.6 kB/s eta 0:00:04
   ----------------------------- ---------- 6.0/8.1 MB 686.6 kB/s eta 0:00:03
   ----------------------------- ---------- 6.0/8.1 MB 686.6 kB/s eta 0:00:03
   ----------------------------- ---------- 6.0/8.1 MB 686.6 kB/s eta 0:00:03
   ----------------------------- ---------- 6.0/8.1 MB 686.6 kB/s eta 0:00:03
   ------------------------------- -------- 6.3/8.1 MB 653.2 kB/s eta 0:00:03
   -------------------------------- ------- 6.6/8.1 MB 669.0 kB/s eta 0:00:03
   -------------------------------- ------- 6.6/8.1 MB 669.0 kB/s eta 0:00:03
   --------------------------------- ------ 6.8/8.1 MB 666.6 kB/s eta 0:00:02
   --------------------------------- ------ 6.8/8.1 MB 666.6 kB/s eta 0:00:02
   --------------------------------- ------ 6.8/8.1 MB 666.6 kB/s eta 0:00:02
   ----------------------------------- ---- 7.1/8.1 MB 652.0 kB/s eta 0:00:02
   ----------------------------------- ---- 7.1/8.1 MB 652.0 kB/s eta 0:00:02
   ------------------------------------ --- 7.3/8.1 MB 643.5 kB/s eta 0:00:02
   ------------------------------------ --- 7.3/8.1 MB 643.5 kB/s eta 0:00:02
   ------------------------------------ --- 7.3/8.1 MB 643.5 kB/s eta 0:00:02
   ------------------------------------- -- 7.6/8.1 MB 638.1 kB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.1 MB 638.1 kB/s eta 0:00:01
   ---------------------------------------  7.9/8.1 MB 632.5 kB/s eta 0:00:01
   ---------------------------------------  7.9/8.1 MB 632.5 kB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 626.6 kB/s eta 0:00:00
Downloading contourpy-1.3.1-cp313-cp313-win_amd64.whl (220 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.56.0-cp313-cp313-win_amd64.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.2 MB 345.2 kB/s eta 0:00:05
   --------- ------------------------------ 0.5/2.2 MB 345.2 kB/s eta 0:00:05
   --------- ------------------------------ 0.5/2.2 MB 345.2 kB/s eta 0:00:05
   --------- ------------------------------ 0.5/2.2 MB 345.2 kB/s eta 0:00:05
   -------------- ------------------------- 0.8/2.2 MB 344.1 kB/s eta 0:00:05
   -------------- ------------------------- 0.8/2.2 MB 344.1 kB/s eta 0:00:05
   -------------- ------------------------- 0.8/2.2 MB 344.1 kB/s eta 0:00:05
   -------------- ------------------------- 0.8/2.2 MB 344.1 kB/s eta 0:00:05
   -------------- ------------------------- 0.8/2.2 MB 344.1 kB/s eta 0:00:05
   ------------------- -------------------- 1.0/2.2 MB 286.6 kB/s eta 0:00:04
   ------------------- -------------------- 1.0/2.2 MB 286.6 kB/s eta 0:00:04
   ------------------- -------------------- 1.0/2.2 MB 286.6 kB/s eta 0:00:04
   ----------------------- ---------------- 1.3/2.2 MB 322.3 kB/s eta 0:00:03
   ---------------------------- ----------- 1.6/2.2 MB 371.7 kB/s eta 0:00:02
   -------------------------------------- - 2.1/2.2 MB 470.6 kB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 478.9 kB/s eta 0:00:00
Downloading kiwisolver-1.4.8-cp313-cp313-win_amd64.whl (71 kB)
Downloading pillow-11.1.0-cp313-cp313-win_amd64.whl (2.6 MB)
   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.6 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.6 MB 916.3 kB/s eta 0:00:03
   ----------- ---------------------------- 0.8/2.6 MB 1.1 MB/s eta 0:00:02
   ----------- ---------------------------- 0.8/2.6 MB 1.1 MB/s eta 0:00:02
   ----------- ---------------------------- 0.8/2.6 MB 1.1 MB/s eta 0:00:02
   --------------- ------------------------ 1.0/2.6 MB 707.6 kB/s eta 0:00:03
   --------------- ------------------------ 1.0/2.6 MB 707.6 kB/s eta 0:00:03
   ------------------- -------------------- 1.3/2.6 MB 647.8 kB/s eta 0:00:03
   ------------------- -------------------- 1.3/2.6 MB 647.8 kB/s eta 0:00:03
   ------------------- -------------------- 1.3/2.6 MB 647.8 kB/s eta 0:00:03
   ------------------- -------------------- 1.3/2.6 MB 647.8 kB/s eta 0:00:03
   ------------------- -------------------- 1.3/2.6 MB 647.8 kB/s eta 0:00:03
   ------------------- -------------------- 1.3/2.6 MB 647.8 kB/s eta 0:00:03
   ------------------- -------------------- 1.3/2.6 MB 647.8 kB/s eta 0:00:03
   ----------------------- ---------------- 1.6/2.6 MB 426.4 kB/s eta 0:00:03
   ----------------------- ---------------- 1.6/2.6 MB 426.4 kB/s eta 0:00:03
   --------------------------- ------------ 1.8/2.6 MB 434.5 kB/s eta 0:00:02
   --------------------------- ------------ 1.8/2.6 MB 434.5 kB/s eta 0:00:02
   --------------------------- ------------ 1.8/2.6 MB 434.5 kB/s eta 0:00:02
   ------------------------------- -------- 2.1/2.6 MB 426.7 kB/s eta 0:00:02
   ----------------------------------- ---- 2.4/2.6 MB 472.4 kB/s eta 0:00:01
   ---------------------------------------- 2.6/2.6 MB 514.0 kB/s eta 0:00:00
Downloading pyparsing-3.2.1-py3-none-any.whl (107 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib
Successfully installed contourpy-1.3.1 cycler-0.12.1 fonttools-4.56.0 kiwisolver-1.4.8 matplotlib-3.10.1 pillow-11.1.0 pyparsing-3.2.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
pip install scipy

Collecting scipy
  Downloading scipy-1.15.2-cp313-cp313-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: numpy<2.5,>=1.23.5 in c:\users\yrahu\appdata\local\programs\python\python313\lib\site-packages (from scipy) (2.2.3)
Downloading scipy-1.15.2-cp313-cp313-win_amd64.whl (41.0 MB)
   ---------------------------------------- 0.0/41.0 MB ? eta -:--:--
   - -------------------------------------- 1.3/41.0 MB 6.6 MB/s eta 0:00:07
   -- ------------------------------------- 2.1/41.0 MB 6.2 MB/s eta 0:00:07
   -- ------------------------------------- 2.6/41.0 MB 3.9 MB/s eta 0:00:10
   -- ------------------------------------- 2.9/41.0 MB 3.3 MB/s eta 0:00:12
   --- ------------------------------------ 3.1/41.0 MB 3.2 MB/s eta 0:00:12
   --- ------------------------------------ 3.4/41.0 MB 2.8 MB/s eta 0:00:14
   --- ------------------------------------ 3.7/41.0 MB 2.6 MB/s eta 0:00:15
   --- ------------------------------------ 3.7/41.0 MB 2.6 MB/s eta 0:00:15
   --- ------------------------------------ 3.7/41.0 MB 2.6 MB/s eta 0:00:15
   --- ------------------------------------ 3.9/41.0 MB 1.7 MB/s eta 0:00:22
   --- ------------------------------------ 3.9/41.0 MB 1.7 MB/s eta 0:00:22
   --- ------------------------------------ 3.9/41.0 MB 1.7 MB/s eta 0:00:22
   --- ------------------------------------ 3.9/41.0 MB 1.7 MB/s eta 0:00:22
   --- ------------------------------------ 3.9/41.0 MB 1.7 MB/s eta 0:00:22
   --- ------------------------------------ 3.9/41.0 MB 1.7 MB/s eta 0:00:22
   --- ------------------------------------ 3.9/41.0 MB 1.7 MB/s eta 0:00:22
   --- ------------------------------------ 3.9/41.0 MB 1.7 MB/s eta 0:00:22
   --- ------------------------------------ 3.9/41.0 MB 1.7 MB/s eta 0:00:22
   ---- ----------------------------------- 4.2/41.0 MB 985.8 kB/s eta 0:00:38
   ---- ----------------------------------- 4.2/41.0 MB 985.8 kB/s eta 0:00:38
   ---- ----------------------------------- 4.5/41.0 MB 952.1 kB/s eta 0:00:39
   ---- ----------------------------------- 4.5/41.0 MB 952.1 kB/s eta 0:00:39
   ---- ----------------------------------- 4.7/41.0 MB 925.0 kB/s eta 0:00:40
   ---- ----------------------------------- 4.7/41.0 MB 925.0 kB/s eta 0:00:40
   ---- ----------------------------------- 4.7/41.0 MB 925.0 kB/s eta 0:00:40
   ---- ----------------------------------- 5.0/41.0 MB 882.2 kB/s eta 0:00:41
   ---- ----------------------------------- 5.0/41.0 MB 882.2 kB/s eta 0:00:41
   ---- ----------------------------------- 5.0/41.0 MB 882.2 kB/s eta 0:00:41
   ----- ---------------------------------- 5.2/41.0 MB 818.2 kB/s eta 0:00:44
   ----- ---------------------------------- 5.2/41.0 MB 818.2 kB/s eta 0:00:44
   ----- ---------------------------------- 5.2/41.0 MB 818.2 kB/s eta 0:00:44
   ----- ---------------------------------- 5.2/41.0 MB 818.2 kB/s eta 0:00:44
   ----- ---------------------------------- 5.5/41.0 MB 744.9 kB/s eta 0:00:48
   ----- ---------------------------------- 5.5/41.0 MB 744.9 kB/s eta 0:00:48
   ----- ---------------------------------- 5.8/41.0 MB 743.5 kB/s eta 0:00:48
   ----- ---------------------------------- 5.8/41.0 MB 743.5 kB/s eta 0:00:48
   ----- ---------------------------------- 5.8/41.0 MB 743.5 kB/s eta 0:00:48
   ----- ---------------------------------- 6.0/41.0 MB 710.1 kB/s eta 0:00:50
   ----- ---------------------------------- 6.0/41.0 MB 710.1 kB/s eta 0:00:50
   ------ --------------------------------- 6.3/41.0 MB 708.5 kB/s eta 0:00:49
   ------ --------------------------------- 6.3/41.0 MB 708.5 kB/s eta 0:00:49
   ------ --------------------------------- 6.6/41.0 MB 715.1 kB/s eta 0:00:49
   ------ --------------------------------- 6.8/41.0 MB 721.5 kB/s eta 0:00:48
   ------ --------------------------------- 7.1/41.0 MB 724.9 kB/s eta 0:00:47
   ------ --------------------------------- 7.1/41.0 MB 724.9 kB/s eta 0:00:47
   ------ --------------------------------- 7.1/41.0 MB 724.9 kB/s eta 0:00:47
   ------- -------------------------------- 7.3/41.0 MB 708.9 kB/s eta 0:00:48
   ------- -------------------------------- 7.6/41.0 MB 718.2 kB/s eta 0:00:47
   ------- -------------------------------- 7.9/41.0 MB 728.8 kB/s eta 0:00:46
   ------- -------------------------------- 8.1/41.0 MB 738.1 kB/s eta 0:00:45
   ------- -------------------------------- 8.1/41.0 MB 738.1 kB/s eta 0:00:45
   -------- ------------------------------- 8.4/41.0 MB 735.5 kB/s eta 0:00:45
   -------- ------------------------------- 8.4/41.0 MB 735.5 kB/s eta 0:00:45
   -------- ------------------------------- 8.7/41.0 MB 734.5 kB/s eta 0:00:44
   -------- ------------------------------- 9.2/41.0 MB 756.8 kB/s eta 0:00:42
   --------- ------------------------------ 9.4/41.0 MB 765.0 kB/s eta 0:00:42
   --------- ------------------------------ 9.7/41.0 MB 772.2 kB/s eta 0:00:41
   --------- ------------------------------ 10.0/41.0 MB 778.8 kB/s eta 0:00:40
   --------- ------------------------------ 10.2/41.0 MB 792.3 kB/s eta 0:00:39
   ---------- ----------------------------- 10.7/41.0 MB 812.7 kB/s eta 0:00:38
   ---------- ----------------------------- 11.0/41.0 MB 825.8 kB/s eta 0:00:37
   ----------- ---------------------------- 11.3/41.0 MB 830.9 kB/s eta 0:00:36
   ----------- ---------------------------- 11.5/41.0 MB 842.4 kB/s eta 0:00:35
   ----------- ---------------------------- 11.8/41.0 MB 838.5 kB/s eta 0:00:35
   ----------- ---------------------------- 11.8/41.0 MB 838.5 kB/s eta 0:00:35
   ----------- ---------------------------- 11.8/41.0 MB 838.5 kB/s eta 0:00:35
   ----------- ---------------------------- 12.1/41.0 MB 822.0 kB/s eta 0:00:36
   ----------- ---------------------------- 12.1/41.0 MB 822.0 kB/s eta 0:00:36
   ------------ --------------------------- 12.3/41.0 MB 815.5 kB/s eta 0:00:36
   ------------ --------------------------- 12.8/41.0 MB 837.5 kB/s eta 0:00:34
   ------------- -------------------------- 13.4/41.0 MB 860.2 kB/s eta 0:00:33
   ------------- -------------------------- 13.6/41.0 MB 865.6 kB/s eta 0:00:32
   ------------- -------------------------- 13.9/41.0 MB 874.2 kB/s eta 0:00:31
   ------------- -------------------------- 14.2/41.0 MB 878.3 kB/s eta 0:00:31
   ------------- -------------------------- 14.2/41.0 MB 878.3 kB/s eta 0:00:31
   -------------- ------------------------- 14.4/41.0 MB 873.8 kB/s eta 0:00:31
   -------------- ------------------------- 14.7/41.0 MB 876.0 kB/s eta 0:00:31
   -------------- ------------------------- 15.2/41.0 MB 890.9 kB/s eta 0:00:29
   --------------- ------------------------ 15.5/41.0 MB 894.6 kB/s eta 0:00:29
   --------------- ------------------------ 15.7/41.0 MB 899.7 kB/s eta 0:00:29
   --------------- ------------------------ 15.7/41.0 MB 899.7 kB/s eta 0:00:29
   --------------- ------------------------ 16.0/41.0 MB 891.4 kB/s eta 0:00:29
   --------------- ------------------------ 16.0/41.0 MB 891.4 kB/s eta 0:00:29
   --------------- ------------------------ 16.3/41.0 MB 884.2 kB/s eta 0:00:28
   ---------------- ----------------------- 16.5/41.0 MB 892.0 kB/s eta 0:00:28
   ---------------- ----------------------- 16.8/41.0 MB 895.9 kB/s eta 0:00:27
   ---------------- ----------------------- 17.0/41.0 MB 900.0 kB/s eta 0:00:27
   ---------------- ----------------------- 17.3/41.0 MB 905.4 kB/s eta 0:00:27
   ----------------- ---------------------- 17.8/41.0 MB 916.3 kB/s eta 0:00:26
   ----------------- ---------------------- 18.1/41.0 MB 926.1 kB/s eta 0:00:25
   ----------------- ---------------------- 18.4/41.0 MB 926.7 kB/s eta 0:00:25
   ----------------- ---------------------- 18.4/41.0 MB 926.7 kB/s eta 0:00:25
   ------------------ --------------------- 18.9/41.0 MB 927.9 kB/s eta 0:00:24
   ------------------ --------------------- 19.1/41.0 MB 933.8 kB/s eta 0:00:24
   ------------------ --------------------- 19.4/41.0 MB 937.9 kB/s eta 0:00:23
   ------------------- -------------------- 19.9/41.0 MB 952.4 kB/s eta 0:00:23
   ------------------- -------------------- 20.4/41.0 MB 968.2 kB/s eta 0:00:22
   ------------------- -------------------- 20.4/41.0 MB 968.2 kB/s eta 0:00:22
   -------------------- ------------------- 21.0/41.0 MB 969.1 kB/s eta 0:00:21
   -------------------- ------------------- 21.2/41.0 MB 975.2 kB/s eta 0:00:21
   --------------------- ------------------ 22.0/41.0 MB 997.9 kB/s eta 0:00:19
   --------------------- ------------------ 22.3/41.0 MB 1.0 MB/s eta 0:00:19
   ---------------------- ----------------- 22.5/41.0 MB 1.0 MB/s eta 0:00:19
   ---------------------- ----------------- 23.1/41.0 MB 1.0 MB/s eta 0:00:18
   ---------------------- ----------------- 23.3/41.0 MB 1.0 MB/s eta 0:00:18
   ----------------------- ---------------- 23.6/41.0 MB 1.0 MB/s eta 0:00:17
   ----------------------- ---------------- 23.9/41.0 MB 1.0 MB/s eta 0:00:17
   ----------------------- ---------------- 24.4/41.0 MB 1.0 MB/s eta 0:00:17
   ------------------------ --------------- 24.9/41.0 MB 1.1 MB/s eta 0:00:16
   ------------------------ --------------- 25.4/41.0 MB 1.1 MB/s eta 0:00:15
   ------------------------ --------------- 25.4/41.0 MB 1.1 MB/s eta 0:00:15
   ------------------------- -------------- 26.2/41.0 MB 1.1 MB/s eta 0:00:14
   ------------------------- -------------- 26.5/41.0 MB 1.1 MB/s eta 0:00:14
   -------------------------- ------------- 27.0/41.0 MB 1.1 MB/s eta 0:00:13
   -------------------------- ------------- 27.5/41.0 MB 1.1 MB/s eta 0:00:13
   --------------------------- ------------ 27.8/41.0 MB 1.1 MB/s eta 0:00:12
   --------------------------- ------------ 28.3/41.0 MB 1.1 MB/s eta 0:00:12
   ---------------------------- ----------- 28.8/41.0 MB 1.1 MB/s eta 0:00:11
   ---------------------------- ----------- 29.4/41.0 MB 1.1 MB/s eta 0:00:11
   ----------------------------- ---------- 30.4/41.0 MB 1.2 MB/s eta 0:00:10
   ----------------------------- ---------- 30.7/41.0 MB 1.2 MB/s eta 0:00:09
   ------------------------------ --------- 30.9/41.0 MB 1.2 MB/s eta 0:00:09
   ------------------------------ --------- 31.5/41.0 MB 1.2 MB/s eta 0:00:09
   ------------------------------- -------- 32.2/41.0 MB 1.2 MB/s eta 0:00:08
   ------------------------------- -------- 32.2/41.0 MB 1.2 MB/s eta 0:00:08
   ------------------------------- -------- 32.8/41.0 MB 1.2 MB/s eta 0:00:07
   -------------------------------- ------- 33.3/41.0 MB 1.2 MB/s eta 0:00:07
   --------------------------------- ------ 33.8/41.0 MB 1.2 MB/s eta 0:00:06
   --------------------------------- ------ 34.3/41.0 MB 1.2 MB/s eta 0:00:06
   --------------------------------- ------ 34.6/41.0 MB 1.2 MB/s eta 0:00:06
   ---------------------------------- ----- 34.9/41.0 MB 1.2 MB/s eta 0:00:05
   ---------------------------------- ----- 35.1/41.0 MB 1.2 MB/s eta 0:00:05
   ---------------------------------- ----- 35.4/41.0 MB 1.2 MB/s eta 0:00:05
   ----------------------------------- ---- 35.9/41.0 MB 1.2 MB/s eta 0:00:05
   ----------------------------------- ---- 36.2/41.0 MB 1.2 MB/s eta 0:00:04
   ----------------------------------- ---- 36.2/41.0 MB 1.2 MB/s eta 0:00:04
   ----------------------------------- ---- 36.2/41.0 MB 1.2 MB/s eta 0:00:04
   ----------------------------------- ---- 36.4/41.0 MB 1.2 MB/s eta 0:00:04
   ----------------------------------- ---- 36.4/41.0 MB 1.2 MB/s eta 0:00:04
   ----------------------------------- ---- 36.4/41.0 MB 1.2 MB/s eta 0:00:04
   ----------------------------------- ---- 36.4/41.0 MB 1.2 MB/s eta 0:00:04
   ----------------------------------- ---- 36.4/41.0 MB 1.2 MB/s eta 0:00:04
   ----------------------------------- ---- 36.4/41.0 MB 1.2 MB/s eta 0:00:04
   ----------------------------------- ---- 36.7/41.0 MB 1.1 MB/s eta 0:00:04
   ------------------------------------ --- 37.0/41.0 MB 1.1 MB/s eta 0:00:04
   ------------------------------------ --- 37.5/41.0 MB 1.1 MB/s eta 0:00:04
   ------------------------------------- -- 38.0/41.0 MB 1.2 MB/s eta 0:00:03
   ------------------------------------- -- 38.3/41.0 MB 1.2 MB/s eta 0:00:03
   ------------------------------------- -- 38.8/41.0 MB 1.2 MB/s eta 0:00:02
   -------------------------------------- - 39.1/41.0 MB 1.2 MB/s eta 0:00:02
   ---------------------------------------  40.1/41.0 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------  40.6/41.0 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------- 41.0/41.0 MB 1.3 MB/s eta 0:00:00
Installing collected packages: scipy
Successfully installed scipy-1.15.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import pandas as np 

import matplotlib.pyplot as plt
# import seaborn as sp

import numpy as np

data ={'month',['January','Fabruary','March','April','May','June','July','August','Septemper','October','November','December'],'Sales (Units)': [110,120,170,140,150,155,180,190,195,210,220,230]
       }

In [ ]:


plt.subplot(1,2,1)
ana.barplot(x='month',y='seles(unit)',data=df.palette='Blues_d'")"
plt.xtitle('month salaes bar char,',fontsize=16)
plt.ytitle('sales(unit)',fontsize=12)
plt.xticks(rotation=45)

login pie char 

plt.subplot(1,2,3)

plt.pie(df['seles(unit)'], labes=df['month],autopct='%1.1f%%', startangle=140)
colors=sns.color_palette('Blues_d',;len(df))
plt.title('sales distribution by month', fontsize=16)

In [3]:
pip install matplotlib

Requirement already satisfied: matplotlib in c:\users\yrahu\appdata\local\programs\python\python313\lib\site-packages (3.10.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\yrahu\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\yrahu\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\yrahu\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\yrahu\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in c:\users\yrahu\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.2.3)
Requirement already satisfied: packaging>=20.0 in c:\users\yrahu\appdata\roaming\python\python313\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\yrahu\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\yrahu\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\yrahu\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\yrahu\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import pandas as pd

import matplotlib.pyplot as plt

In [6]:
plt.plot(df['month'],df['sales (units)'],
          marker='0',color='b',linesstyle='-',markersize=8)

NameError: name 'df' is not defined

In [ ]:
#convert the data into a data Frame 
df=pd.DataFrame(data)

df['moving avarage (3 MONOTH)']=df['sales(units)'].rolling(window=3).mean

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'